CREATE DEFINER=`root`@`%` PROCEDURE `AvoidRelations`(IN GivenID  VARCHAR(255),IN subStrUserName VARCHAR(255),IN needChild BOOLEAN)
BEGIN
    DECLARE rv VARCHAR(4000);
    SELECT GetFamilyTree(GivenID,needChild) INTO rv;
    DROP TABLE IF EXISTS RELATION_TABLE;
    CREATE TEMPORARY TABLE RELATION_TABLE(USERID VARCHAR(255),USERNAME VARCHAR(255),USERPOSITION VARCHAR(255));
    INSERT INTO RELATION_TABLE(USERID,USERNAME,USERPOSITION) SELECT id,CONCAT_WS(' ',first_name,last_name),IFNULL(POSITION,'') FROM ETEC_USER WHERE NOT FIND_IN_SET(id,rv);
    SELECT USERID,CONCAT(USERNAME,IF(LENGTH(USERPOSITION) > 0,CONCAT(' (',USERPOSITION,')'),'')) AS USERNAME FROM RELATION_TABLE WHERE USERNAME LIKE CONCAT('%',subStrUserName,'%');
    DROP TABLE IF EXISTS RELATION_TABLE;
END 